In [83]:
print("he")

he


In [84]:
! pip install numpy

<!-- python -m venv "env name" 
env name /script/activate
detavtivate
pip install numpy -->

In [85]:
import numpy as np 

In [86]:
print("Numpy Version",np.__version__)

Numpy Version 2.4.6


In [87]:
lst =[1,2,34,67,7]
print("this is my first list",lst)
print(type(lst))
arr = np.array(lst)
print("this is my array after typecasting:",arr)
print(type(arr))

this is my first list [1, 2, 34, 67, 7]
<class 'list'>
this is my array after typecasting: [ 1  2 34 67  7]
<class 'numpy.ndarray'>


In [88]:
lst = list(range(0,20))

In [89]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [90]:
arr = np.array(lst)


In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [92]:
arr = np.array([1,23,465,7])

In [93]:
arr

array([  1,  23, 465,   7])

In [94]:
arr = np.arange(0,25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [95]:
arr =np.zeros(20)

In [96]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [97]:
arr=np.zeros((0,20))

In [98]:
arr

array([], shape=(0, 20), dtype=float64)

In [99]:
arr=np.linspace(1,2,10)

In [100]:
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [101]:
arr = np.arange(0,60)

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [103]:
arr.reshape(30,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59]])

In [104]:
arr.reshape(10,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [105]:
arr.reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [106]:
arr.reshape(6,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [107]:
arr.reshape(15,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [108]:
# c=a.reshape(12,5)
# a.shape  #gives the shape of the array a
# a.ndim  #gives the number of dimensions of the array a
# a.size  #gives the total number of elements in the array a
# a.dtype  #gives the data type of the elements in the array a
# print(c)
# print(c.shape)
# print(c.ndim)
# print(c.size)
# print(c.dtype)

In [109]:
arr.reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [129]:
arr = arr.reshape(12,5)
print("gives the shape of the array",arr.shape)
print("gives the number of dimensions of the array",arr.ndim)
print("gives the data type of the elements in the array",arr.dtype)
print("gives the total number of elements in the array",arr.size)

gives the shape of the array (12, 5)
gives the number of dimensions of the array 2
gives the data type of the elements in the array int64
gives the total number of elements in the array 60


In [111]:
arr[1,1]

np.int64(6)

In [112]:
arr[0,0]

np.int64(0)

In [113]:
arr[1,4]

np.int64(9)

In [114]:
arr[-1,-1]

np.int64(59)

In [115]:
arr[11,4]

np.int64(59)

In [116]:
arr[-1,4]

np.int64(59)

In [117]:
arr[-2,4]

np.int64(54)

In [118]:
arr[-2,3]

np.int64(53)

In [119]:
arr[10,4]

np.int64(54)

In [120]:
arr[11,-1]

np.int64(59)

In [121]:
arr[0]

array([0, 1, 2, 3, 4])

In [122]:
arr[1]

array([5, 6, 7, 8, 9])

In [123]:
arr[3]

array([15, 16, 17, 18, 19])

In [124]:
arr[(3,4)]

np.int64(19)

In [125]:
arr[3:4]

array([[15, 16, 17, 18, 19]])

In [126]:
arr[3:4,2]

array([17])

In [127]:
arr[7:9]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [128]:
arr[7:9,1:3]

array([[36, 37],
       [41, 42]])