In [130]:
print("he")

he


In [131]:
! pip install numpy

<!-- python -m venv "env name" 
env name /script/activate
detavtivate
pip install numpy -->

In [132]:
import numpy as np 

In [133]:
print("Numpy Version",np.__version__)

Numpy Version 2.4.6


In [134]:
lst =[1,2,34,67,7]
print("this is my first list",lst)
print(type(lst))
arr = np.array(lst)
print("this is my array after typecasting:",arr)
print(type(arr))

this is my first list [1, 2, 34, 67, 7]
<class 'list'>
this is my array after typecasting: [ 1  2 34 67  7]
<class 'numpy.ndarray'>


In [135]:
lst = list(range(0,20))

In [136]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [137]:
arr = np.array(lst)


In [138]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [139]:
arr = np.array([1,23,465,7])

In [140]:
arr

array([  1,  23, 465,   7])

In [141]:
arr = np.arange(0,25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [142]:
arr =np.zeros(20)

In [143]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [144]:
arr=np.zeros((0,20))

In [145]:
arr

array([], shape=(0, 20), dtype=float64)

In [146]:
arr=np.linspace(1,2,10)

In [147]:
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [148]:
arr = np.arange(0,60)

In [149]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [150]:
arr.reshape(30,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59]])

In [151]:
arr.reshape(10,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [152]:
arr.reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [153]:
arr.reshape(6,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [154]:
arr.reshape(15,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [155]:
# c=a.reshape(12,5)
# a.shape  #gives the shape of the array a
# a.ndim  #gives the number of dimensions of the array a
# a.size  #gives the total number of elements in the array a
# a.dtype  #gives the data type of the elements in the array a
# print(c)
# print(c.shape)
# print(c.ndim)
# print(c.size)
# print(c.dtype)

In [156]:
arr.reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [157]:
arr = arr.reshape(12,5)
print("gives the shape of the array",arr.shape)
print("gives the number of dimensions of the array",arr.ndim)
print("gives the data type of the elements in the array",arr.dtype)
print("gives the total number of elements in the array",arr.size)

gives the shape of the array (12, 5)
gives the number of dimensions of the array 2
gives the data type of the elements in the array int64
gives the total number of elements in the array 60


In [158]:
arr[1,1]

np.int64(6)

In [159]:
arr[0,0]

np.int64(0)

In [160]:
arr[1,4]

np.int64(9)

In [161]:
arr[-1,-1]

np.int64(59)

In [162]:
arr[11,4]

np.int64(59)

In [163]:
arr[-1,4]

np.int64(59)

In [164]:
arr[-2,4]

np.int64(54)

In [165]:
arr[-2,3]

np.int64(53)

In [166]:
arr[10,4]

np.int64(54)

In [167]:
arr[11,-1]

np.int64(59)

In [168]:
arr[0]

array([0, 1, 2, 3, 4])

In [169]:
arr[1]

array([5, 6, 7, 8, 9])

In [170]:
arr[3]

array([15, 16, 17, 18, 19])

In [171]:
arr[(3,4)]

np.int64(19)

In [172]:
arr[3:4]

array([[15, 16, 17, 18, 19]])

In [173]:
arr[3:4,2]

array([17])

In [174]:
arr[7:9]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [175]:
arr[7:9,1:3]

array([[36, 37],
       [41, 42]])

In [180]:
arr = np.arange(15,3,5)

In [181]:
arr

array([], dtype=int64)

In [182]:
arr=np.arange(225).reshape(5,3,15)

In [183]:
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14],
        [ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
          27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44]],

       [[ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
          57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
          72,  73,  74],
        [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
          87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
         102, 103, 104],
        [105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
         117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
         132, 133, 134]],

       [[135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
         147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 

In [184]:
arr=np.arange(225).reshape(5,15,3)  # 5 is table
# 15 is row 
# 3 is colunm

In [185]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [186]:
arr[0,0,0]

np.int64(0)

In [187]:
arr[0:4,0,0]

array([  0,  45,  90, 135])

In [188]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [189]:
arr[1]

array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [190]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [191]:
arr[3]

array([[135, 136, 137],
       [138, 139, 140],
       [141, 142, 143],
       [144, 145, 146],
       [147, 148, 149],
       [150, 151, 152],
       [153, 154, 155],
       [156, 157, 158],
       [159, 160, 161],
       [162, 163, 164],
       [165, 166, 167],
       [168, 169, 170],
       [171, 172, 173],
       [174, 175, 176],
       [177, 178, 179]])

In [192]:
arr[4]

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [194]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [195]:
arr[1:3,0,0]

array([45, 90])

In [196]:
arr[1:1,1,1]

array([], dtype=int64)

In [197]:
arr[0:5,0:1]

array([[[  0,   1,   2]],

       [[ 45,  46,  47]],

       [[ 90,  91,  92]],

       [[135, 136, 137]],

       [[180, 181, 182]]])

In [198]:
arr[0:5,0:2]

array([[[  0,   1,   2],
        [  3,   4,   5]],

       [[ 45,  46,  47],
        [ 48,  49,  50]],

       [[ 90,  91,  92],
        [ 93,  94,  95]],

       [[135, 136, 137],
        [138, 139, 140]],

       [[180, 181, 182],
        [183, 184, 185]]])

In [203]:
arr[0:5,-1,-1]

array([ 44,  89, 134, 179, 224])

In [204]:
arr[0:5,-2,-2]

array([ 40,  85, 130, 175, 220])

In [205]:
arr[0:5,1,1]

array([  4,  49,  94, 139, 184])

In [206]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [210]:
arr[0:1,-1,-1]

array([44])

In [211]:
arr[0:2,-1,-1]

array([44, 89])

In [212]:
arr[0:5,1,1]

array([  4,  49,  94, 139, 184])

In [214]:
arr[0:1,1:4]

array([[[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

In [216]:
arr[0:3,2:5]

array([[[  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14]],

       [[ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59]],

       [[ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104]]])

In [217]:
arr[0:1,0:2,0:3]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [218]:
arr[0:5,0:3,0:3]

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98]],

       [[135, 136, 137],
        [138, 139, 140],
        [141, 142, 143]],

       [[180, 181, 182],
        [183, 184, 185],
        [186, 187, 188]]])

In [219]:
arr[0,:,1]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43])

In [220]:
arr[0,1,:]

array([3, 4, 5])

In [221]:
arr[-1,-1,-1]

np.int64(224)

In [224]:
arr[0:1,-1,-1] = 78

In [225]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  78]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [230]:
arr[0:1,-2,-2] = 89

In [231]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  89,  41],
        [ 42,  43,  78]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [232]:
# arr = arr.reshape(12,5)
print("gives the shape of the array",arr.shape)
print("gives the number of dimensions of the array",arr.ndim)
print("gives the data type of the elements in the array",arr.dtype)
print("gives the total number of elements in the array",arr.size)

gives the shape of the array (5, 15, 3)
gives the number of dimensions of the array 3
gives the data type of the elements in the array int64
gives the total number of elements in the array 225


In [233]:
arr.flatten() # used in deep learning

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  89,  41,  42,  43,  78,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [234]:
arr.ravel() # convert into one d array


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  89,  41,  42,  43,  78,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

| Feature                        | `flatten()`             | `ravel()`                             |
| ------------------------------ | ----------------------- | ------------------------------------- |
| Returns                        | A **copy** of the array | A **view** of the array (if possible) |
| Memory                         | Creates new memory      | Uses existing memory                  |
| Speed                          | Slower                  | Faster                                |
| Changes affect original array? | ❌ No                    | ✅ Yes (usually)                       |


overloading,overriding,super(),constructor,multithreading,processing,function overloading,opertor overloading,basic python

In [ ]:
new_list = list(range(1, 11))
new_list